SET DEFINE OFF

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('1', 'Anglais', 'Mariama', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('2', 'Science de l''Education ', 'Mariama	', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('3', 'Sociologie', 'Mariama', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('4', 'SEG', 'Amy Collé ', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('5', 'SP', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('6', 'SJ', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('7', 'AES', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('8', 'Droit et Informatique-Legal Tech', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('9', 'MACG', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('10', 'DPAP', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('11', 'DPIP', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('12', 'MDPR', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('13', 'Finance-Comptabilité', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('14', 'EEDD', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('15', 'MGRH', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('16', 'MCTDL', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('17', 'PSD', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('18', 'PMP', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('19', 'Capacité en Droit', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('20', 'AGN', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('21', 'DA', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('22', 'MAI', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('23', 'MIC', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('24', 'MMASN', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('25', 'SIMAC', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('26', 'GNB', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('27', 'Robotique', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('28', 'Big Data Analytics', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('29', 'Cybersécurité', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('30', 'Intelligence Artificielle', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('31', 'Ingenierie Logicielle', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('32', 'MSRIV', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('33', 'Calcul Scientifique', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('34', 'MRCC', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('35', 'CAGEE', 'Mariama', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('36', 'CPE', 'Mariama', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('37', 'CT', 'Mariama', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('38', 'Administration Economique et Sociale', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('39', 'Sciences Economiques et de Gestion', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('40', 'Sciences Juridiques', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('41', 'Audit et controle de Gestion', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('42', 'Collectivités Territorial et Developpement local', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('43', 'Droit PrivéDroit PublicManagement stratégique et conseil en GRH', 'Amy Collé', 'Barry', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('44', 'Certificat Internet et Libertés', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('45', 'CDFMRRCM', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('46', 'CICMCMM', 'Amy Collé', 'Barry', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('47', 'Developpement d''Application', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('48', 'MAI', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('49', 'Arts graphiques et Numériques', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('50', 'Communication Digitale', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('51', 'Multimédia Internet Communication', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('52', 'SIMC', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('53', 'MMASN', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('54', 'Systemes Reseaux et Infrastructures virtuelles', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('55', 'Realisation et Creation Cinématographiques', 'Salimata', 'Faye', 'Professeur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('56', 'Certificat Developpement Logiciel', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('57', 'Certificat Securité', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('58', 'Certificat Administrateur Moodle', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('59', 'CME', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('60', 'Certificat Language de Programmation Python', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('61', 'Certificat Moodle Enseignement', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('62', 'Certificat introduction à l''IOT', 'Salimata', 'Faye', 'Docteur');

INSERT INTO FILIERE (ID_FILIERE, NOM_FILIERE, PRENOM_RESPONSABLE, NOM_RESPONSABLE, COLUMN1) 
VALUES ('63', 'CertificatConstruire et Parametrer un réseau IOT', 'Salimata', 'Faye', 'Docteur');

SELECT * FROM FILIERE;