select*from PREINSCRIPTION;
select*from POLE;
delete from POLE;
select* from POLE;
select*from FILIERE;
select*from FORMATION;


select*from ENO;
select*from ZONE;

select* from INSCRIPTION where STATUT='Inscrit';
select*from NIVEAU;
 select DATE_INSCRIPTION from INSCRIPTION;
select * from FILIERE where EXTRACT(YEAR FROM DATE_PREINSCRIPTION)=2019 JOIN SYSTEM.PREINSCRIPTION
  ON FILIERE.ID_FILIERE = ETUDIANT.ID_ETUDIANT;
select*from INSCRIPTION where DATE_INSCRIPTION= YEAR(DATE_INSCRIPTION);
select*from PREINSCRIPTION where STATUT='Non inscrit';
select*from ETUDIANT;
delete from ETUDIANT;
select*from NIVEAU;


SELECT
  ETUDIANT.NOM_ETUDIANT,
  ETUDIANT.PRENOM_ETUDIANT,
  FILIERE.NOM_FILIERE,
  INSCRIPTION.DATE_INSCRIPTION,
  INSCRIPTION.STATUT,
FROM SYSTEM.ETUDIANT
JOIN SYSTEM.FILIERE@zonecapvertsite1
  ON FILIERE.ID_FILIERE = ETUDIANT.ID_ETUDIANT
  
  
  
  
  SELECT FILIERE.NOM_ETUDIANT
FROM ETUDIANT
JOIN SYSTEM.PREINSCRIPTION ON ETUDIANT.ID = SYSTEM.PREINSCRIPTION
GROUP BY ETUDIANT.ID
HAVING COUNT(SYSTEM.PREINSCRIPTION.ID) > 1;


select*from PREINSCRIPTION;


SELECT ETUDIANT.NOM_ETUDIANT, COUNT(ETUDIANT.ID_ETUDIANT) AS NOMBRE_ETUDIANT
FROM ETUDIANT
JOIN FILIERE ON FILIERE.ID = ETUDIANT.ID
WHERE FILIERE.NOM_FILIERE = 'Anglais'
GROUP BY ETUDIANT.NOM_ETUDIANT
HAVING COUNT(ETUDIANT.ID_ETUDIANT) >23;




SELECT *FROM FILIERE COUNT(PREINSCRIPTION.IDPRES) AS NOMBRE_PREINSCRIPTION 
JOIN PREINSCRIPTION ON FILIERE.ID_FILIERE=PREINSCRIPTION.IDPRES WHERE 
EXTRACT(YEAR FROM PREINSCRIPTION.DATE_PRESINCRIPTION)=2019 
GROUP BY FILIERE.NOM_FILIERE
HAVING COUNT (PREINSCRIPTION.IDPRES)>5;

___________________
SELECT*
FROM ETUDIANT
INNER JOIN INSCRIPTION ON ETUDIANT.ID_ETUDIANT = INSCRIPTION.IDINS
WHERE EXTRACT(YEAR FROM INSCRIPTION.DATE_INSCRIPTION)=2021;

SELECT ETUDIANT.NOM_ETUDIANT,ETUDIANT.PRENOM_ETUDIANT,FILIERE.NOM_FILIERE,ENO.NOM_ENO,INSCRIPTION.DATE_INSCRIPTION,INSCRIPTION.STATUT,ZONE.NOMZONE FROM ETUDIANT JOIN FILIERE ON FILIERE.ID_FILIERE = ETUDIANT.ID_ETUDIANT JOIN ENO ON ENO.IDENO = ETUDIANT.ID_ETUDIANT JOIN ZONE ON ZONE.IDZONE = ENO.IDENO JOIN INSCRIPTION ON INSCRIPTION.IDINS = ETUDIANT.ID_ETUDIANT AND EXTRACT(YEAR FROM DATE_INSCRIPTION)=2019;

SELECT NOM_FILIERE, COUNT(PREINSCRIPTION.IDPRES) AS NOMBRE_PREINSCRIPTION FROM FILIERE JOIN PREINSCRIPTION ON FILIERE.ID_FILIERE=PREINSCRIPTION.IDPRES WHERE EXTRACT(YEAR FROM PREINSCRIPTION.DATE_PRESINCRIPTION)=2019 GROUP BY FILIERE.NOM_FILIERE HAVING COUNT (PREINSCRIPTION.IDPRES)>1;__________________

SELECT* FROM ETUDIANT INNER JOIN INSCRIPTION ON ETUDIANT.ID_ETUDIANT = INSCRIPTION.IDINS WHERE EXTRACT(YEAR FROM INSCRIPTION.DATE_INSCRIPTION)=2021;

SELECT*
FROM ETUDIANT
JOIN ZONE ON ZONE.IDZONE = ETUDIANT.ID_ETUDIANT
JOIN PREINSCRIPTION ON PREINSCRIPTION.IDPRES = ETUDIANT.ID_ETUDIANT
JOIN INSCRIPTION ON INSCRIPTION.IDINS = ETUDIANT.ID_ETUDIANT
WHERE  EXTRACT(YEAR FROM INSCRIPTION.DATE_INSCRIPTION)=2021
___________________________




delete from ETUDIANT;
select* from ETUDIANT;